baseurl = "https://www.danielemaltese.com/"
title = "malte"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Daniele Maltese"
    description = "Italian Junior Developer with a lot of things in mind."
    keywords = "blog,developer,personal"
    info = "Full Stack Dreamer"
    avatarurl = "images/avatar.png"
    footercontent = "I'm just trying to act cool."

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#    siteID = "ABCDE"
#    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ilmalte/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 1
    url = "https://instagram.com/ilmalte/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"

	    # [[languages.en.menu.main]]
            # name = "About"
            # weight = 2
            # url = "about/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    # [languages.it]
        # languagename = "Italian"

        # [languages.it.params]
            # info = "Full Stack testa di cazzo"
            # description = "Sito personale di Daniele Maltese"
            # keywords = "blog,sviluppatore,personale"
            # footercontent = "Coloque algum texto aqui."

        # [languages.it.menu]
	    # [[languages.it.menu.main]]
            # name = "Blog"
            # weight = 1
            # url = "posts/"

            # [[languages.it.menu.main]]
            # name = "About"
            # weight = 2
            # url = "about/"

            # [[languages.it.menu.main]]
            # name = "Progetti"
            # weight = 3
            # url = "projects/"

            # [[languages.it.menu.main]]
            # name = "Contattami"
            # weight = 5
            #url = "contact/"
